# Generated by Django 5.2.3 on 2025-06-26 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('death_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('elo_rating', models.FloatField(default=1200)),
            ],
            options={
                'ordering': ['-elo_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('form', models.CharField(blank=True, help_text='e.g., novel, poem, play', max_length=64)),
                ('elo_rating', models.FloatField(default=1200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='core.author')),
            ],
            options={
                'ordering': ['-elo_rating', 'title'],
                'unique_together': {('title', 'author')},
            },
        ),
    ]
