# Generated by Django 5.2.4 on 2025-07-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='Full Wikipedia URL (e.g., https://en.wikipedia.org/wiki/William_Shakespeare)'),
        ),
        migrations.AddField(
            model_name='work',
            name='wikipedia_url',
            field=models.URLField(blank=True, help_text='Full Wikipedia URL (e.g., https://en.wikipedia.org/wiki/Ulysses_(novel))'),
        ),
    ]
