# Generated by Django 5.2.4 on 2025-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_wikipedia_url_work_wikipedia_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('author', 'Author'), ('work', 'Work')], max_length=10)),
                ('item_a_id', models.PositiveIntegerField()),
                ('item_b_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'item_a_id', 'item_b_id'], name='core_compar_content_432d79_idx'), models.Index(fields=['created_at'], name='core_compar_created_385eb3_idx')],
            },
        ),
    ]
