# Generated by Django 5.2.4 on 2025-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comparison'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comparison',
            name='core_compar_created_385eb3_idx',
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='elo_rating',
            field=models.FloatField(db_index=True, default=1200),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='content_type',
            field=models.CharField(choices=[('author', 'Author'), ('work', 'Work')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='item_a_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='item_b_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='elo_rating',
            field=models.FloatField(db_index=True, default=1200),
        ),
        migrations.AlterField(
            model_name='work',
            name='form',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., novel, poem, play', max_length=64),
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['-elo_rating', 'name'], name='core_author_elo_rat_c13fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['birth_year', 'death_year'], name='core_author_birth_y_5fdea2_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['content_type', 'created_at'], name='core_compar_content_918442_idx'),
        ),
        migrations.AddIndex(
            model_name='comparison',
            index=models.Index(fields=['-created_at'], name='core_compar_created_5d54b2_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['-elo_rating', 'title'], name='core_work_elo_rat_39cce4_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['author', '-elo_rating'], name='core_work_author__43a149_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['form', '-elo_rating'], name='core_work_form_ca969c_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['publication_year'], name='core_work_publica_d05c47_idx'),
        ),
    ]
