# Generated by Django 5.2.4 on 2025-07-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mysql_optimization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='wikipedia_url',
        ),
        migrations.RemoveField(
            model_name='work',
            name='wikipedia_url',
        ),
    ]
