# Generated by Django 6.0.4 on 2026-04-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_wikipedia_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('author', 'Author'), ('work', 'Work')], db_index=True, max_length=10)),
                ('item_a_id', models.PositiveIntegerField(db_index=True)),
                ('item_b_id', models.PositiveIntegerField(db_index=True)),
                ('winner', models.CharField(choices=[('A', 'A wins'), ('B', 'B wins')], max_length=1)),
                ('elo_a_before', models.FloatField()),
                ('elo_b_before', models.FloatField()),
                ('elo_a_after', models.FloatField()),
                ('elo_b_after', models.FloatField()),
                ('model_used', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'item_a_id'], name='core_llmmat_content_61e819_idx'), models.Index(fields=['content_type', 'item_b_id'], name='core_llmmat_content_baeeed_idx'), models.Index(fields=['content_type', '-created_at'], name='core_llmmat_content_e161a4_idx')],
            },
        ),
    ]
