# Generated by Django 6.0.4 on 2026-04-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mlaib_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comparison',
            name='core_compar_content_432d79_idx',
        ),
        migrations.RemoveIndex(
            model_name='comparison',
            name='core_compar_content_918442_idx',
        ),
        migrations.RemoveIndex(
            model_name='comparison',
            name='core_compar_created_5d54b2_idx',
        ),
        migrations.DeleteModel(
            name='Comparison',
        ),
    ]
