# Generated by Django 6.0.4 on 2026-04-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_comparison_core_compar_content_432d79_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='viaf_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
