# Generated by Django 6.0.4 on 2026-04-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_author_viaf_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='wikipedia_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
